server:
  servlet:
    context-path: /eshop
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:watches
    username: admin
    password: none
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect